name: GlxNapThe
main: napthe/napthe
author: Justin
version: 1.0.0
api: 2.0.0
commands:
   napvip:
      description: NapVip Command.
      usage: /napvip
   napxu:
      description: Napxu Command
permissions:
    napvip.command:
        description: Allows you to use command.
        default: true
